Tests that evaluation in console that throws works fine when script is paused.

Set timer for test function.
Dumping console messages:

injectedFunction()
debugger-eval-while-paused-throws.js:54 Uncaught Error: injectedObj.func
    at Object.func (debugger-eval-while-…sed-throws.js:54:15)
    at injectedFunction (debugger-eval-while-…sed-throws.js:57:24)
    at eval (eval at testFunction (inspected-page.html:30:11), <anonymous>:1:1)
    at testFunction (test.js:30:11)
func @ debugger-eval-while-paused-throws.js:54
injectedFunction @ debugger-eval-while-paused-throws.js:57
eval @ VM:1
testFunction @ test.js:30
setTimeout (async)
scheduleTestFunction @ VM:3
(anonymous) @ VM:1
localObj.func()
test.js:27 Uncaught Error: localObj.func
    at Object.func (test.js:27:25)
    at eval (eval at testFunction (inspected-page.html:30:11), <anonymous>:1:10)
    at testFunction (test.js:30:11)
func @ test.js:27
eval @ VM:1
testFunction @ test.js:30
setTimeout (async)
scheduleTestFunction @ VM:3
(anonymous) @ VM:1
globalObj.func()
test.js:18 Uncaught Error: globalObj.func
    at Object.func (test.js:18:21)
    at eval (eval at testFunction (inspected-page.html:30:11), <anonymous>:1:11)
    at testFunction (test.js:30:11)
func @ test.js:18
eval @ VM:1
testFunction @ test.js:30
setTimeout (async)
scheduleTestFunction @ VM:3
(anonymous) @ VM:1

