This is a testharness.js-based test.
PASS Throw Error in toplevel: classic: listener
PASS Throw Error in toplevel: classic: handler
PASS Throw Error in toplevel: module: listener
PASS Throw Error in toplevel: module: handler
FAIL Throw DOMException-TypeError in toplevel: classic: listener assert_regexp_match: e.message should contain the message of the thrown error expected object "/Throw in/" but got "Uncaught "
FAIL Throw DOMException-TypeError in toplevel: classic: handler assert_regexp_match: e.message should contain the message of the thrown error expected object "/Throw in/" but got "Uncaught "
FAIL Throw DOMException-TypeError in toplevel: module: listener assert_regexp_match: e.message should contain the message of the thrown error expected object "/Throw in/" but got "Uncaught "
FAIL Throw DOMException-TypeError in toplevel: module: handler assert_regexp_match: e.message should contain the message of the thrown error expected object "/Throw in/" but got "Uncaught "
PASS Throw Error in setTimeout-function: classic: listener
PASS Throw Error in setTimeout-function: classic: handler
PASS Throw Error in setTimeout-function: module: listener
PASS Throw Error in setTimeout-function: module: handler
PASS Throw DOMException-TypeError in setTimeout-function: classic: listener
PASS Throw DOMException-TypeError in setTimeout-function: classic: handler
PASS Throw DOMException-TypeError in setTimeout-function: module: listener
PASS Throw DOMException-TypeError in setTimeout-function: module: handler
PASS Throw Error in setTimeout-string: classic: listener
PASS Throw Error in setTimeout-string: classic: handler
PASS Throw Error in setTimeout-string: module: listener
PASS Throw Error in setTimeout-string: module: handler
FAIL Throw DOMException-TypeError in setTimeout-string: classic: listener assert_regexp_match: e.message should contain the message of the thrown error expected object "/Throw in/" but got "Uncaught "
FAIL Throw DOMException-TypeError in setTimeout-string: classic: handler assert_regexp_match: e.message should contain the message of the thrown error expected object "/Throw in/" but got "Uncaught "
FAIL Throw DOMException-TypeError in setTimeout-string: module: listener assert_regexp_match: e.message should contain the message of the thrown error expected object "/Throw in/" but got "Uncaught "
FAIL Throw DOMException-TypeError in setTimeout-string: module: handler assert_regexp_match: e.message should contain the message of the thrown error expected object "/Throw in/" but got "Uncaught "
PASS Throw Error in onmessage: classic: listener
PASS Throw Error in onmessage: classic: handler
PASS Throw Error in onmessage: module: listener
PASS Throw Error in onmessage: module: handler
PASS Throw DOMException-TypeError in onmessage: classic: listener
PASS Throw DOMException-TypeError in onmessage: classic: handler
PASS Throw DOMException-TypeError in onmessage: module: listener
PASS Throw DOMException-TypeError in onmessage: module: handler
PASS Throw Error in onerror: classic: listener
PASS Throw Error in onerror: classic: handler
PASS Throw Error in onerror: module: listener
PASS Throw Error in onerror: module: handler
PASS Throw DOMException-TypeError in onerror: classic: listener
PASS Throw DOMException-TypeError in onerror: classic: handler
PASS Throw DOMException-TypeError in onerror: module: listener
PASS Throw DOMException-TypeError in onerror: module: handler
Harness: the test ran to completion.

